// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package go_micro_lzx_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 用户名称
type Username struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Username) Reset()         { *m = Username{} }
func (m *Username) String() string { return proto.CompactTextString(m) }
func (*Username) ProtoMessage()    {}
func (*Username) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0ad046c4a28cace0, []int{0}
}
func (m *Username) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Username.Unmarshal(m, b)
}
func (m *Username) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Username.Marshal(b, m, deterministic)
}
func (dst *Username) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Username.Merge(dst, src)
}
func (m *Username) XXX_Size() int {
	return xxx_messageInfo_Username.Size(m)
}
func (m *Username) XXX_DiscardUnknown() {
	xxx_messageInfo_Username.DiscardUnknown(m)
}

var xxx_messageInfo_Username proto.InternalMessageInfo

func (m *Username) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 返回的用户时间
type UserTimeResponse struct {
	Time                 int32    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTimeResponse) Reset()         { *m = UserTimeResponse{} }
func (m *UserTimeResponse) String() string { return proto.CompactTextString(m) }
func (*UserTimeResponse) ProtoMessage()    {}
func (*UserTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0ad046c4a28cace0, []int{1}
}
func (m *UserTimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTimeResponse.Unmarshal(m, b)
}
func (m *UserTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTimeResponse.Marshal(b, m, deterministic)
}
func (dst *UserTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTimeResponse.Merge(dst, src)
}
func (m *UserTimeResponse) XXX_Size() int {
	return xxx_messageInfo_UserTimeResponse.Size(m)
}
func (m *UserTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserTimeResponse proto.InternalMessageInfo

func (m *UserTimeResponse) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Username)(nil), "go.micro.lzx.user.Username")
	proto.RegisterType((*UserTimeResponse)(nil), "go.micro.lzx.user.UserTimeResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_0ad046c4a28cace0) }

var fileDescriptor_user_0ad046c4a28cace0 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4c, 0xcf, 0xd7, 0xcb, 0xcd, 0x4c, 0x2e, 0xca,
	0xd7, 0xcb, 0xa9, 0xaa, 0xd0, 0x03, 0x49, 0x28, 0xc9, 0x71, 0x71, 0x84, 0x16, 0xa7, 0x16, 0xe5,
	0x25, 0xe6, 0xa6, 0x0a, 0x09, 0x71, 0xb1, 0x80, 0x68, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x30, 0x5b, 0x49, 0x8d, 0x4b, 0x00, 0x24, 0x1f, 0x92, 0x99, 0x9b, 0x1a, 0x94, 0x5a, 0x5c, 0x90,
	0x9f, 0x57, 0x0c, 0x56, 0x57, 0x92, 0x09, 0x55, 0xc7, 0x1a, 0x04, 0x66, 0x1b, 0xa5, 0x72, 0x71,
	0x83, 0xcc, 0x0b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x0a, 0xe3, 0x12, 0x70, 0x4f, 0x2d,
	0x01, 0xe9, 0xf2, 0x2f, 0x72, 0x4c, 0x49, 0x01, 0x19, 0x21, 0x24, 0xad, 0x87, 0x61, 0xbd, 0x1e,
	0xcc, 0x6e, 0x29, 0x65, 0x1c, 0x92, 0xc8, 0x16, 0x2b, 0x31, 0x24, 0xb1, 0x81, 0x3d, 0x62, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x38, 0x4a, 0xf6, 0xd6, 0x00, 0x00, 0x00,
}
